"use strict";

export const REQUEST_SENT = "REQUEST_SENT";
export const REQUEST_RECEIVED_SUCCESSFUL = "REQUEST_RECEIVED_SUCCESSFUL";
export const REQUEST_RECEIVED_ERROR = "REQUEST_RECEIVED_ERROR";

export const RETRIEVE_ALL_ARTICLES = "RETRIEVE_ALL_ARTICLES";
